import Head from "next/head"
import React from "react"
import Header from "@/components/Header"
import AddTodo from "@/components/AddTodo"
import { TodoItem } from "@/components/TodoItem"

export default function Home() {
  const [list, setList] = React.useState([])

  React.useEffect(() => {
    const localData = localStorage.getItem("List")
    setList(() => (localData !== null ? JSON.parse(localData) : []))
  }, [])

  function addTodo(task: any) {
    if (task.text !== "") {
      setList((prevValue: any) => {
        return [...prevValue, { id: task.id, text: task.text }]
      })
    }
  }

  function deleteTodo(id: string) {
    setList(() => {
      return list.filter((task: any) => task.id !== id)
    })
  }

  React.useEffect(() => {
    localStorage.setItem("List", JSON.stringify(list))
  }, [list])

  return (
    <>
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#FFFEF2] h-[100vh] px-8">
        <Header />
        <AddTodo onAdd={addTodo} />
        {list &&
          list.map((todo: any) => (
            <TodoItem
              key={todo.id}
              Id={todo.id}
              text={todo.text}
              Delete={deleteTodo}
            />
          ))}
      </main>
    </>
  )
}
